# Generated by Django 4.2.9 on 2024-04-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ecg_Page',
        ),
    ]
