# Generated by Django 4.2.9 on 2024-05-04 22:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgpage',
            name='classification',
            field=wagtail.fields.StreamField([('prediction', wagtail.blocks.StructBlock([('predicted_label', wagtail.blocks.ChoiceBlock(choices=[('F', 'F'), ('M', 'M'), ('N', 'N'), ('V', 'V'), ('S', 'S'), ('Q', 'Q')], help_text='Choose the label')), ('description', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=True),
        ),
    ]
