# Generated by Django 4.2.9 on 2024-05-06 21:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('ecg', '0006_ecgpage_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcgResult2',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('label', models.CharField(choices=[('F', 'F'), ('M', 'M'), ('N', 'N'), ('Q', 'Q'), ('S', 'S'), ('V', 'V')], help_text='This is important', max_length=1)),
                ('discription', wagtail.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
