# Generated by Django 4.2.9 on 2024-05-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0007_ecgresult2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EcgResult2',
        ),
    ]
