# Generated by Django 4.2.9 on 2024-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
