# Generated by Django 4.2.9 on 2024-04-05 21:49

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiggle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('components', wagtail.fields.StreamField([('banner_carousel', wagtail.blocks.StructBlock([('slides', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('slide_header', wagtail.blocks.CharBlock()), ('slide_subheader', wagtail.blocks.CharBlock()), ('slide_image', wagtail.images.blocks.ImageChooserBlock()), ('slide_redirect_link', wagtail.blocks.PageChooserBlock(required=False))])))])), ('about_us', wagtail.blocks.StructBlock([('img1', wagtail.images.blocks.ImageChooserBlock()), ('img2', wagtail.images.blocks.ImageChooserBlock(required=False)), ('pre_header', wagtail.blocks.CharBlock()), ('main_header', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.TextBlock()), ('page_redirect', wagtail.blocks.PageChooserBlock(required=False))])), ('page_intro', wagtail.blocks.BooleanBlock(default=True)), ('blog_section', wagtail.blocks.StructBlock([('pre_header', wagtail.blocks.CharBlock()), ('header', wagtail.blocks.CharBlock()), ('sub_header', wagtail.blocks.CharBlock())])), ('team_section', wagtail.blocks.StructBlock([('pre_header', wagtail.blocks.CharBlock()), ('header', wagtail.blocks.CharBlock())])), ('fact_band', wagtail.blocks.StructBlock([('facts', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.IntegerBlock()), ('fact', wagtail.blocks.CharBlock(max_length=50))])))]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_description', models.CharField(blank=True)),
                ('component', wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='image for the paragraph', required=False)), ('image_position', wagtail.blocks.ChoiceBlock(choices=[('L', 'Left Aligned'), ('R', 'Right Aligned')], help_text='Image position (default Center)', required=False)), ('body', wagtail.blocks.RichTextBlock())])), ('fact_band', wagtail.blocks.StructBlock([('facts', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.IntegerBlock()), ('fact', wagtail.blocks.CharBlock(max_length=50))])))]))], blank=True, use_json_field=True)),
                ('blog_list_header', models.CharField(blank=True, default='Other Blogs', max_length=20, null=True)),
                ('show_advertisement', models.BooleanField(blank=True, default=True)),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
