# Generated by Django 4.2.9 on 2024-04-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
