# Generated by Django 4.2.9 on 2024-04-07 20:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name1', models.CharField(blank=True, max_length=15, null=True)),
                ('name2', models.CharField(max_length=15)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
                ('redirect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='NavTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nav_title', models.CharField(blank=True, help_text='Ignore if single page / external link', max_length=20, null=True)),
                ('nav_links', wagtail.fields.StreamField([('Website_Page', wagtail.blocks.PageChooserBlock()), ('External_Link', wagtail.blocks.StructBlock([('Title', wagtail.blocks.CharBlock()), ('URL', wagtail.blocks.URLBlock())]))], use_json_field=True)),
                ('navbar', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_tab', to='menus.navbar')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
