# Generated by Django 4.2.9 on 2024-04-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navtab',
            name='nav_title',
            field=models.CharField(blank=True, help_text='Enter for Dropdown list', max_length=20, null=True),
        ),
    ]
